# SPDX-FileCopyrightText: 2025 Stefan Haun <tux@netz39.de>
# SPDX-License-Identifier: MIT
---

- name: Add deb822-style Docker's APT repository
  ansible.builtin.template:
    src: templates/docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.sources
    owner: root
    group: root
    mode: '0644'
  register: apt_repo

- name: Remove old-style Docker's APT repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
