# SPDX-FileCopyrightText: 2020 Stefan Haun <tux@netz39.de>
# SPDX-License-Identifier: MIT
---
# handlers file for host-docker
- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: yes
